# Dependencies
spark.jars.packages io.delta:delta-spark_2.13:4.4.0,org.apache.spark:spark-sql-kafka-0-10_2.13:4.2.0,com.microsoft.sqlserver:mssql-jdbc:13.4.0.jre11,org.apache.hadoop:hadoop-aws:3.5.0

# Spark cluster
spark.master spark://spark-master:7077

# Delta Lake
spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog

# Hive Metastore
spark.sql.catalogImplementation hive
spark.hadoop.hive.metastore.uris thrift://hive:9083
spark.sql.hive.metastore.version 4.1.0
spark.sql.hive.metastore.jars maven

# MinIO / S3A
spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false

# Spark History Server
spark.eventLog.enabled true
spark.eventLog.dir s3a://spark-events/
spark.history.fs.logDirectory s3a://spark-events/